### PR TITLE
Unicode 12 update

### PR DESCRIPTION
**Pull request by MHumm**
I updated the block definitions of JclUnicode according to unicode.org, version 12. I am not sure if this is everything necessary for implementation of Unicode 12 support, but it's a start.

### CODE REVIEW

**Comment by MHumm** [comment]
This fixes (if it's all one needs to do for supporting Unicode 12) Mantis issue 6679.
[http://issuetracker.delphi-jedi.org/view.php?id=6679](http://issuetracker.delphi-jedi.org/view.php?id=6679)

**Comment by MHumm** [comment]
Looks like I messed up with Git once again. Commit 
3f5355e should not be in here, but how do I get it out of this as painlessly as possible?

**Comment by petr-nehez** [comment]
The easiest way for you would be making a new branch from `master` and then doing interactive rebase of `MHumm:6679_Unicode_12_Update` onto your new branch where the commit you don't want to include would be marked as "drop".
And finaly it would be better to open a new PR and close this one.

**Comment by ronaldhoek** [comment]
> Looks like I messed up with Git once again. Commit
> [3f5355e](https://github.com/project-jedi/jcl/commit/3f5355edf08db986d590c2bbe114c047fda9162e) should not be in here, but how do I get it out of this as painlessly as possible?

You could also do a revert of the changes en commit those again - then there won't be any changes regarding the file anymore.

**Comment by MHumm** [comment]
Due to issues with this request I close it and propose a less problematic one here:
[https://github.com/project-jedi/jcl/pull/63](https://github.com/project-jedi/jcl/pull/63)

**Comment by MHumm** [comment]
Due to issues with this request I close it and propose a less problematic one here:
[https://github.com/project-jedi/jcl/pull/63](https://github.com/project-jedi/jcl/pull/63)

**Pull request closed without merging**
