### PR TITLE
Installing under Delphi Community Edition 10.3

### PR DESCRIPTION
**Pull request by Guba666**
I'd trying to re-learn programming after many years.
I's like to install JEDI components, and I'm using the Community Edition of Delphi 10.3
I0d like to know if it is possible to install here.
Also I'd like to know how uninstall JEDI if this doesn't fit to my needs.
Thank you very much for the help to this proobie.

### CODE REVIEW

**Comment by ronaldhoek** [comment]
Why are you trying to merge your change with an old tag?

**Comment by Guba666** [comment]
Dear Ronald,

I haven't the smallest idea of what you're talking about.
I'm a perfect beginner with git hub, and I have to try to understand it.
Why it is so apparently difficult to use....
What I'm asking is that I'd like to know if I can install the JEDI
components with Delphi 10.3 Community edition.
Just that.
If I have done something wrong please don't flame me.
Thanks for any suggestion/cooperation you'll offer to me.
Thanks

Sergio Bonfiglio


Il giorno lun 30 mar 2020 alle ore 08:39 Ronald Hoek <
notifications@github.com> ha scritto:

**Comment by ronaldhoek** [comment]
Hi Sergio,

Well, you've opened a pull request at Github to ask the maintainer to merge the projects 'master' branch into the branch 'JCL_2.7':
image

So, therefore, my question.

> I'm a perfect beginner with git hub, and I have to try to understand it.
> Why it is so apparently difficult to use....

But if you want to learn more about Github I suggest you start with the Guthub tutorials first!
See: https://lab.github.com/

Second about how to (un)install JEDI see: 
https://github.com/project-jedi/jvcl/blob/master/readme.md

**Comment by Guba666** [comment]
Dear Ronald,

thanks for the reply, also however it is unclear to me.
I'll read the git tutorial,s I promise, but now I have a work issue to
solve.
Could you please point me at the right direction ?
I need to know where to ask and/or who ask to, if it is possible to install
this JEDI version (2.7 if I have correctly understood) under Delphi 10.3
Community Edition.
Just that.
Please help me if you can. It is a work issue.
Thanks a lot.

Sergio
Italy


Il giorno lun 30 mar 2020 alle ore 14:11 Ronald Hoek <
notifications@github.com> ha scritto:

**Comment by jfudickar** [comment]
Hi Sergio,
I would suggest to do a new full clone from the repository and try to install it.
Don't know why you are using such an old version.
Both JCL and JVCL are able to be installed with the 10.3 community edition.
I did the same last week. No change is needed to get it installed.
Regards
Jens

**Comment by Guba666** [comment]
Dear Jens

thanks for the kind reply.
I do not understand why you say that Delphi 10.3 is old. I mean the 10.3
Rio version, probably I haven't been clear.
Thanks for the note.
I will try to install it, after a complete backup of the whole Delphi
installation.
As far as you can have realized, all it seems so fragile inside Delphi.
Move or change something and everything stops to work.
As well as it was at my old times. I'm trying to re-learn programming
today, after several years of different work, but it seems to me that
Delphi is so little less buggy than the old XE7, the last one I used and
the version that frustrated me so much to convince me to change type of
job, dedicating myself to what I can to better, that is to be an
entrepreneur in commercial activities.
Now, with this coronavirus mess, I'm doing nothing - all my activities are
temporary closed - and so I decided to try to find new opportunities with
my old projects.
Thank you for your help.
Stay home safe and take care of yourself. Here is a hell.
Sergio
Italy


Il giorno mar 31 mar 2020 alle ore 23:54 Jens Fudickar <
notifications@github.com> ha scritto:

**Comment by ronaldhoek** [comment]
Hi Sergio,

> I do not understand why you say that Delphi 10.3 is old.

Looks like you are not reading it correctly.

With the following sentence of @jfudickar :
> Don't know why you are using such an old version.

He is referring to the 2.7 version of the JCL library you are using

> Delphi is so little less buggy than the old XE7
Well, I can't agree completely with you on this.
It's not more/less buggy then Visual Studio.

It all depends on the stability of packages your using with the IDE.

But there are some problems, which can be fixed using @ahausladen 's IDE fix pack: https://www.idefixpack.de/blog/ide-tools/ide-fix-pack/

**Comment by ronaldhoek** [comment]
But please I suggest you now close the pull request, as it adds to many assumptions to your question AND second 'pull request' are not for support!

Please go to the newsgroups for support: https://newsportal.delphi-jedi.org/

And use this link to start a new thread:
https://newsportal.delphi-jedi.org/post.php?newsgroups=jedi.jvcl&type=new

**Comment by Guba666** [comment]
As requested I (tried to do...) have closed the pull request.
Hope I did it correctly.
I will use the two links (support and newsgroups) for the future.
Thanks for your help and not having flamed me.

Sergio


Il giorno mer 1 apr 2020 alle ore 14:08 Ronald Hoek <
notifications@github.com> ha scritto:

**Pull request closed without merging**
