### PR TITLE
Tweaked Windows 10 detection and added Windows 10 release functions in JclSysInfo.pas

### PR DESCRIPTION
**Pull request by cycocrew**
* Tweaked Windows 10 detection in JclSysInfo.pas
* Added following Windows 10 release functions to JclSysInfo.pas:
  - GetWindows10ReleaseId
  - GetWindows10ReleaseName
  - GetWindows10ReleaseCodeName
  - GetWindows10ReleaseVersion

### CODE REVIEW

**Comment by obones** [comment]
Why add specific functions for Windows 10 when there are none for the others?

**Comment by cycocrew** [comment]
There is not such concept before Windows 10. With Windows 10, see each release as Windows 10.0 (Initial Release), Windows 10.1 (November Update), Windows 10.2 (Anniversary Update), etc., except that there is no such numbering scheme.

**Comment by ronaldhoek** [comment]
Why not leave out the '10' specifier... If this is realy something MS is thinking of keeping for the future, one can expect the next Windows version to have the same info.
```
GetWindowsReleaseId
GetWindowsReleaseName
GetWindowsReleaseCodeName
GetWindowsReleaseVersion
```
Of course,  it should be documented these routines only work Windows 10 and up.

**Comment by cycocrew** [comment]
Note that the next version of Windows will still be called Windows 10. As there's no visibility beyond Windows 10 as a whole, I thought that making it explicit was the way to go. But your suggestion may work.

**Comment by markjforte** [comment]
FYI, according to Microsoft, Windows 10 is supposed to be the last major version.  Future "versions" will be updates similar to the "Anniversary Update".  As a result, I am for keeping the existing function names as-is (i.e. "GetWindows10Release...").

**Comment by cycocrew** [comment]
Is there more discussion needed here? Additional functions are Windows 10 specific and it seems that Microsoft won't be moving away from Windows 10 terminology for a while, so the "GetWindows10" naming seems appropriate here.

Note that this pull request also contains a tweak for Windows 10 detection which would be useful to get committed in trunk.

**Comment by ronaldhoek** [comment]
No more discussion needed form my part. I'm fine with the naming too.

**Pull request merged**
