### PR TITLE
Unit tests jcl math tests3

### PR DESCRIPTION
**Pull request by MHumm**
Implemented further JclMath unit tests. Can you please just pick the changes to TestJclMath? Until the other pull requests are I I fear my new pull requests created are polluted by unwanted files. This is because I don't fully understand Git yet. Sorry!

### CODE REVIEW

**Comment by MHumm** [comment]
When trying to fix this pull request by interactively rebasing it I get this failure:
"error: could not apply edaa555db... Added tests for DoubleToHex and HexToDouble
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply edaa555db... Added tests for DoubleToHex and HexToDouble
Auto-merging qa/automated/dunit/units/TestJclMath.pas
CONFLICT (content): Merge conflict in qa/automated/dunit/units/TestJclMath.pas"

Can somebody please help me to fix this?

**Comment by obones** [comment]
The easiest way here is to restart from scratch:

Switch to master
Pull changes from "upstream" into your master
Create a new branch and switch to it
Copy over the required changed files
Recreate the commits by hand
Push everything
Create a new Pull request

**Comment by MHumm** [comment]
I tried but failed. It always has 11 commits and most of them containing old stuff and merges. I followed your advice. I don't know what recreate commits by hand means, but I saved the files I wanted to update and after creating the branch I copied them over again, did a commit and then a push. But instead of just containing my one commit the pull request contains 11 commits!

What did I do wrong?

**Comment by MHumm** [comment]
Superceeded by #98

**Pull request closed without merging**
