### PR TITLE
Using all chars on hash

### PR DESCRIPTION
**Pull request by marcelo-rocha**
case insensitive hash function is ignoring the last char

### CODE REVIEW

**Comment by obones** [comment]
If you look at the top of the file, you will see this:

    WARNING:  JEDI preprocessor generated unit.  Do not edit. 

This means this unit should not be edited directly but rather via the one in the prototypes folder.

**Comment by marcelo-rocha** [comment]
commit adjusted

**Comment by obones** [comment]
Thanks, I see now that I was not clear in my answer. Basically, both files must be changed: The prototype, and the final one.
In your original commit, the prototype was missing so the final file would be overwritten upon next generation.
In this commit, the final file is missing, which means the fix is not available until a new generation is done.

Can you add another commit to this branch so that the final file is also modified?

**Comment by marcelo-rocha** [comment]
commit added

**Pull request merged**
